import Header from "@/components/layout/auth/Header";

export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
      <>
          <Header />
          {children}
      </>
  );
}
