import Header from "@/components/layout/user/Header";

export const metadata = {
  title: "Google Reviews",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
      <>
          <Header />
          {children}
      </>
  );
}
